# These are supported funding model platforms

custom:["https://www.paypal.com/cgi-bin/webscr?business=info%40sakuraryoko.com&cmd=_donations&currency_code=USD&item_name=Donation+to+Sakura+Ryoko&return=http%3A%2F%2Fsakuraryoko.com%2Fhome"]
